version: "3.7"

networks:
  traefik:

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entryPoints.websecure.address=:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik

  nginx_node:
    image: nginx
    environment:
      - NGINX_HOST=${HOST_LARAVEL_VUE}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.nginx_laravel.entrypoints=web"
      - "traefik.http.routers.nginx_laravel.rule=HostRegexp(`{domain:.+}`)"
      - "traefik.http.routers.nginx_laravel.priority=1"
      - "traefik.http.routers.nginx_laravel.service=nginx_laravel"
      - "traefik.http.services.nginx_laravel.loadbalancer.server.port=80"
    volumes:
      - './docker/nginx:/etc/nginx/conf.d/'
      - './backend/laravel:/var/www'
    networks:
      - traefik

  nginx_laravel:
    image: nginx
    environment:
      - NGINX_HOST=${HOST_LARAVEL_VUE}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.nginx_laravel.entrypoints=web"
      - "traefik.http.routers.nginx_laravel.rule=HostRegexp(`{domain:.+}`)"
      - "traefik.http.routers.nginx_laravel.priority=1"
      - "traefik.http.routers.nginx_laravel.service=nginx_laravel"
      - "traefik.http.services.nginx_laravel.loadbalancer.server.port=80"
    volumes:
      - './docker/nginx:/etc/nginx/conf.d/'
      - './backend/laravel:.'
    networks:
      - traefik
    links:
      - laravel
    depends_on:
      - laravel

  laravel:
    build:
      args:
        user: 'sammy'
        uid: '1000'
      context: './docker/php'
      dockerfile: Dockerfile
    restart: 'unless-stopped'
    working_dir: '/var/www/'
    image: 'laravel-list'
    expose:
      - '9000'
    volumes:
      - './backend/laravel:/var/www'
    labels:
      - "traefik.enable=false"
    networks:
      - traefik

  node-server:
    build:
      context: '.'
      dockerfile: ./docker/node/Dockerfile
    container_name: node-server
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.node-server.entrypoints=web"
      - "traefik.http.routers.node-server.rule=Host(`traefik.docker.node`)" # work with /api
      - "traefik.http.routers.node-server.priority=1"
      - "traefik.http.routers.node-server.service=node-server"
      - "traefik.http.services.node-server.loadbalancer.server.port=80"
    volumes:
      - './backend/node:/app'
    networks:
      - traefik
    tty: true